


### SEEND FETCH SONGS REQUEST 
GET http://localhost:3000/songs


### SEEND FETCH SONG REQUEST BY ID 
GET http://localhost:3000/songs/1



### CREATE SONG REQUEST
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "Song number 1",
    "artist": "Artist number 1",
    "releasedDate": "2025-04-08",
    "duration": "02:34"
}


### Update SONG REQUEST
PUT  http://localhost:3000/songs/1




### Delete SONG REQUEST
DELETE   http://localhost:3000/songs/1


